apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangodemo-deployment
spec:
  selector:
    matchLabels:
      app: djangodemo
  template:
    metadata:
      labels:
        app: djangodemo
    spec:
      containers:
      - name: djangodemo
        image: djangodemo:v2.5
        ports:
        - containerPort: 8000