apiVersion: apps/v1
kind: Deployment
metadata:
  name: djangodemodb-deployment
spec:
  selector:
    matchLabels:
      app: djangodemodb
  template:
    metadata:
      labels:
        app: djangodemodb
    spec:
      containers:
      - name: djangodemodb
        image: postgres
        ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: djangodemodbvolume

volumes:
  name: djangodemodbvolume
  persistentVolumeClaim:
    claimName: djangodemodbvolume