apiVersion: v1
kind: PersistentVolume
metadata:
  name: djangodemodbvolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/jpmeyer/projects/jp/minikubelearning/djangodemo/djangodemo/db-data"